import { StudentRecord, KpiSummary } from "@/types";

export const INITIAL_STUDENTS: StudentRecord[] = [
  {
    id: "rec_on_9012",
    airtableRecordId: "recK8x912aBc3d",
    fullName: "Marcus Vance",
    phone: "+1 (416) 555-0194",
    email: "marcus.vance@rogers.com",
    city: "Toronto",
    province: "ON",
    originalProgramInterest: "Cybersecurity & Cloud Operations",
    currentEmploymentStatus: "Part-time / Underemployed",
    leadSource: "TorontoDiplomaFinder-LandingPage",
    dateCollected: "2024-02-14",
    staleDays: 580,
    verificationStatus: "Verified & Interested",
    dialAttempts: 1,
    lastDialedAt: "Today, 10:14 AM EST",
    callDurationSec: 142,
    verifiedDetails: {
      identityConfirmed: true,
      confirmedProgram: "Cybersecurity & Cloud Operations",
      confirmedCity: "Toronto",
      confirmedEmployment: "Part-time / Underemployed",
      lookingToEnrol: true,
      targetIntake: "Immediate (Next 30 Days)",
      tuitionAcknowledged: true,
      consentToShareTimestamp: "2026-09-15T14:16:22.108Z",
      consentVerbalQuote: "Yes, I understand it's tuition-based and you have my verbal permission to connect me with the admissions team.",
      consentSha256: "crtc_7f2b1a99a4b2c8e1f03d57",
      dispositionNote: "Highly motivated prospect. Meets laptop hardware requirements. Ready for morning cohort.",
      assignedPartnerCollege: "triOS College - Toronto Campus",
      transferOutcome: "Warm Transfer Completed",
      recordingUrl: "https://audio-cdn.ontariovoice.ca/rec_on_9012.mp3",
      costCad: 0.44,
    },
    callTranscript: [
      {
        id: "t1",
        speaker: "agent",
        text: "Hello, this is Sarah, an automated AI admissions assistant calling on behalf of Ontario Career College Admissions. This call is recorded for quality and compliance. Am I speaking with Marcus Vance?",
        timestampSec: 2,
        complianceTag: "CRTC_AI_DISCLOSURE",
      },
      {
        id: "t2",
        speaker: "student",
        text: "Hey, yes, this is Marcus.",
        timestampSec: 7,
      },
      {
        id: "t3",
        speaker: "agent",
        text: "Great to speak with you, Marcus! You previously requested information about the Cybersecurity diploma program in Toronto. Are you still located in Toronto?",
        timestampSec: 12,
        complianceTag: "IDENTITY_VERIFICATION",
      },
      {
        id: "t4",
        speaker: "student",
        text: "Yeah, still in downtown Toronto. Working retail part-time right now.",
        timestampSec: 18,
      },
      {
        id: "t5",
        speaker: "agent",
        text: "Understood. Are you still actively looking to enrol in a college program, and what timeframe?",
        timestampSec: 24,
      },
      {
        id: "t6",
        speaker: "student",
        text: "Definitely. I want to transition into tech as soon as possible, ideally next month.",
        timestampSec: 30,
      },
      {
        id: "t7",
        speaker: "agent",
        text: "That's great. To be completely upfront: these are tuition-based diploma programs at licensed Ontario career colleges—they are not free government training, and there are no guaranteed jobs. Does that fit your expectations?",
        timestampSec: 38,
        complianceTag: "TUITION_EXPECTATIONS",
      },
      {
        id: "t8",
        speaker: "student",
        text: "Yes, I know OSAP or student loans apply, that's fine.",
        timestampSec: 46,
      },
      {
        id: "t9",
        speaker: "agent",
        text: "Perfect. Do we have your verbal consent to share your contact details with our partner college admissions team for a priority call?",
        timestampSec: 54,
        complianceTag: "VERBAL_CONSENT_CAPTURED",
      },
      {
        id: "t10",
        speaker: "student",
        text: "Yes, you have my permission.",
        timestampSec: 59,
      },
      {
        id: "t11",
        speaker: "agent",
        text: "Thank you, Marcus. Transferring you to our senior admissions coordinator now.",
        timestampSec: 64,
        complianceTag: "WARM_TRANSFER_INITIATED",
      },
    ],
  },
  {
    id: "rec_on_9013",
    airtableRecordId: "recL9y023bCd4e",
    fullName: "Priya Patel",
    phone: "+1 (905) 555-0812",
    email: "priya.patel@gmail.com",
    city: "Mississauga",
    province: "ON",
    originalProgramInterest: "Practical Nursing Diploma",
    currentEmploymentStatus: "Employed (Looking for Career Change)",
    leadSource: "HealthcareCareers-Quiz-2024",
    dateCollected: "2024-06-10",
    staleDays: 462,
    verificationStatus: "Pending Dial",
    dialAttempts: 0,
  },
  {
    id: "rec_on_9014",
    airtableRecordId: "recM1z134cDe5f",
    fullName: "Devon Tremblay",
    phone: "+1 (647) 555-0239",
    email: "devon.t@sympatico.ca",
    city: "Brampton",
    province: "ON",
    originalProgramInterest: "Supply Chain & Logistics",
    currentEmploymentStatus: "Unemployed / Seeking Work",
    leadSource: "OntarioCareerQuiz-MetaAds",
    dateCollected: "2023-11-20",
    staleDays: 665,
    verificationStatus: "Not Interested / Closed",
    dialAttempts: 1,
    lastDialedAt: "Yesterday, 2:45 PM EST",
    callDurationSec: 52,
    verifiedDetails: {
      identityConfirmed: true,
      confirmedProgram: "Supply Chain & Logistics",
      confirmedCity: "Brampton",
      confirmedEmployment: "Full-Time Employed",
      lookingToEnrol: false,
      targetIntake: "Not Looking",
      tuitionAcknowledged: false,
      dispositionNote: "Secured permanent full-time position as warehouse supervisor last month. Closed politely.",
      costCad: 0.28,
    },
  },
  {
    id: "rec_on_9015",
    airtableRecordId: "recN2a245dEf6g",
    fullName: "Sarah Al-Mansoor",
    phone: "+1 (905) 555-0471",
    email: "sarah.almansoor@outlook.com",
    city: "Hamilton",
    province: "ON",
    originalProgramInterest: "Paralegal (Law Society Accredited)",
    currentEmploymentStatus: "Part-time / Underemployed",
    leadSource: "LegalCareersOntario-Quiz",
    dateCollected: "2024-01-08",
    staleDays: 616,
    verificationStatus: "Verified & Interested",
    dialAttempts: 2,
    lastDialedAt: "Today, 11:30 AM EST",
    callDurationSec: 165,
    verifiedDetails: {
      identityConfirmed: true,
      confirmedProgram: "Paralegal (Law Society Accredited)",
      confirmedCity: "Hamilton",
      confirmedEmployment: "Legal Assistant",
      lookingToEnrol: true,
      targetIntake: "Fall 2026",
      tuitionAcknowledged: true,
      consentToShareTimestamp: "2026-09-15T15:32:08.411Z",
      consentVerbalQuote: "Yes, I understand and agree to pass my info to the college admissions officer.",
      consentSha256: "crtc_8a3c2e11b5c3d9f2a14e68",
      dispositionNote: "Has legal assistant background. Seeking LSO licensing qualification. Booked callback.",
      assignedPartnerCollege: "Medix College - Hamilton Campus",
      transferOutcome: "Admissions Callback Booked",
      bookingSlot: "Tomorrow, 2:00 PM EST",
      costCad: 0.51,
    },
  },
  {
    id: "rec_on_9016",
    airtableRecordId: "recP3b356eFg7h",
    fullName: "Jason MacLeod",
    phone: "+1 (519) 555-0983",
    email: "jason.macleod@bell.net",
    city: "London",
    province: "ON",
    originalProgramInterest: "Network Administration",
    currentEmploymentStatus: "Unemployed / Seeking Work",
    leadSource: "OntarioCareerQuiz-MetaAds",
    dateCollected: "2023-09-15",
    staleDays: 730,
    verificationStatus: "Invalid / Disconnected",
    dialAttempts: 3,
    lastDialedAt: "Today, 9:20 AM EST",
    callDurationSec: 14,
    verifiedDetails: {
      identityConfirmed: false,
      confirmedProgram: "Network Administration",
      confirmedCity: "London",
      confirmedEmployment: "Unknown",
      lookingToEnrol: false,
      targetIntake: "Not Looking",
      tuitionAcknowledged: false,
      dispositionNote: "Telco SIT tone received: 'The number you have dialed is not in service'. Marked for database scrub.",
      costCad: 0.08,
    },
  },
  {
    id: "rec_on_9017",
    airtableRecordId: "recQ4c467fGh8j",
    fullName: "Fatima El-Sayed",
    phone: "+1 (613) 555-0341",
    email: "fatima.elsayed@gmail.com",
    city: "Ottawa",
    province: "ON",
    originalProgramInterest: "Medical Office Administrator",
    currentEmploymentStatus: "Unemployed / Seeking Work",
    leadSource: "HealthcareCareers-Quiz-2024",
    dateCollected: "2024-05-02",
    staleDays: 501,
    verificationStatus: "Pending Dial",
    dialAttempts: 0,
  },
  {
    id: "rec_on_9018",
    airtableRecordId: "recR5d578gHi9k",
    fullName: "Brandon O'Connor",
    phone: "+1 (905) 555-0722",
    email: "brandon.oc@yahoo.ca",
    city: "Oshawa",
    province: "ON",
    originalProgramInterest: "Cybersecurity & Cloud Operations",
    currentEmploymentStatus: "Employed (Looking for Career Change)",
    leadSource: "TorontoDiplomaFinder-LandingPage",
    dateCollected: "2023-12-05",
    staleDays: 650,
    verificationStatus: "DNC Opt-Out (Permanent)",
    dialAttempts: 1,
    lastDialedAt: "Today, 10:05 AM EST",
    callDurationSec: 22,
    verifiedDetails: {
      identityConfirmed: true,
      confirmedProgram: "Cybersecurity & Cloud Operations",
      confirmedCity: "Oshawa",
      confirmedEmployment: "Unknown",
      lookingToEnrol: false,
      targetIntake: "Not Looking",
      tuitionAcknowledged: false,
      dispositionNote: "Student explicitly requested: 'Take me off your list and do not call again'. Immediately added to National & Internal DNC Registry.",
      costCad: 0.12,
    },
  },
  {
    id: "rec_on_9019",
    airtableRecordId: "recS6e689hIj0l",
    fullName: "Chloe Zhang",
    phone: "+1 (905) 555-0158",
    email: "chloe.zhang@markham.ca",
    city: "Markham",
    province: "ON",
    originalProgramInterest: "Digital Marketing & E-Commerce",
    currentEmploymentStatus: "Part-time / Underemployed",
    leadSource: "CareerQuiz2024-FB",
    dateCollected: "2024-04-20",
    staleDays: 513,
    verificationStatus: "Verified & Interested",
    dialAttempts: 1,
    lastDialedAt: "Today, 11:45 AM EST",
    callDurationSec: 138,
    verifiedDetails: {
      identityConfirmed: true,
      confirmedProgram: "Digital Marketing & E-Commerce",
      confirmedCity: "Markham",
      confirmedEmployment: "Part-time / Underemployed",
      lookingToEnrol: true,
      targetIntake: "Immediate (Next 30 Days)",
      tuitionAcknowledged: true,
      consentToShareTimestamp: "2026-09-15T15:47:10.220Z",
      consentVerbalQuote: "Yes, I agree to share my details with the college admissions staff.",
      consentSha256: "crtc_9b4d3f22c6d4e0a3b25f79",
      dispositionNote: "Ready to start October class. Wants hybrid evening format.",
      assignedPartnerCollege: "Oxford College - Markham Campus",
      transferOutcome: "Warm Transfer Completed",
      costCad: 0.42,
    },
  },
  {
    id: "rec_on_9020",
    airtableRecordId: "recT7f790iJk1m",
    fullName: "Aiden Kowalski",
    phone: "+1 (519) 555-0639",
    email: "a.kowalski@rogers.com",
    city: "Kitchener",
    province: "ON",
    originalProgramInterest: "Supply Chain & Logistics",
    currentEmploymentStatus: "Unemployed / Seeking Work",
    leadSource: "OntarioCareerQuiz-MetaAds",
    dateCollected: "2024-03-11",
    staleDays: 553,
    verificationStatus: "Wrong Person / Reassigned",
    dialAttempts: 1,
    lastDialedAt: "Today, 9:55 AM EST",
    callDurationSec: 29,
    verifiedDetails: {
      identityConfirmed: false,
      confirmedProgram: "Supply Chain & Logistics",
      confirmedCity: "Kitchener",
      confirmedEmployment: "Unknown",
      lookingToEnrol: false,
      targetIntake: "Not Looking",
      tuitionAcknowledged: false,
      dispositionNote: "Answered by homeowner stating Aiden moved away 18 months ago. Number reassigned.",
      costCad: 0.15,
    },
  },
  {
    id: "rec_on_9021",
    airtableRecordId: "recU8g801jKl2n",
    fullName: "Nathalie Dubois",
    phone: "+1 (613) 555-0914",
    email: "nathalie.dubois@videotron.ca",
    city: "Ottawa",
    province: "ON",
    originalProgramInterest: "Personal Support Worker (PSW)",
    currentEmploymentStatus: "Unemployed / Seeking Work",
    leadSource: "HealthcareCareers-Quiz-2024",
    dateCollected: "2024-07-15",
    staleDays: 427,
    verificationStatus: "Retry Scheduled",
    dialAttempts: 1,
    lastDialedAt: "Today, 10:30 AM EST",
    callDurationSec: 18,
    verifiedDetails: {
      identityConfirmed: false,
      confirmedProgram: "Personal Support Worker (PSW)",
      confirmedCity: "Ottawa",
      confirmedEmployment: "Unknown",
      lookingToEnrol: false,
      targetIntake: "Undecided",
      tuitionAcknowledged: false,
      dispositionNote: "Voicemail reached. Automated compliant AI disclosure left. Re-queueing in 4 hours.",
      costCad: 0.09,
    },
  },
  {
    id: "rec_on_9022",
    airtableRecordId: "recV9h912kLm3o",
    fullName: "Tariq Mansoor",
    phone: "+1 (416) 555-0763",
    email: "tariq.m@hotmail.com",
    city: "Scarborough",
    province: "ON",
    originalProgramInterest: "Cybersecurity & Cloud Operations",
    currentEmploymentStatus: "Part-time / Underemployed",
    leadSource: "TorontoDiplomaFinder-LandingPage",
    dateCollected: "2024-02-28",
    staleDays: 566,
    verificationStatus: "Pending Dial",
    dialAttempts: 0,
  },
  {
    id: "rec_on_9023",
    airtableRecordId: "recW0i023lMn4p",
    fullName: "Jessica Campbell",
    phone: "+1 (519) 555-0842",
    email: "jess.campbell@cogeco.ca",
    city: "Windsor",
    province: "ON",
    originalProgramInterest: "Medical Office Administrator",
    currentEmploymentStatus: "Unemployed / Seeking Work",
    leadSource: "CareerQuiz2024-FB",
    dateCollected: "2023-10-18",
    staleDays: 698,
    verificationStatus: "Pending Dial",
    dialAttempts: 0,
  },
];

export const INITIAL_KPI_SUMMARY: KpiSummary = {
  totalRecords: 15240,
  dialedCount: 8430,
  connectedCount: 5766,
  connectRatePct: 68.4,
  intentConfirmedCount: 1837,
  intentConfirmedRatePct: 21.8,
  staleBadNumberCount: 2874,
  staleBadNumberPct: 34.1,
  dncOptOutCount: 412,
  verbalConsentCount: 1837,
  avgCallDurationSec: 114,
  totalCostCad: 3540.6,
  costPerConfirmedLeadCad: 1.93,
};
